### ISSUE TITLE
Does it work with other web framework like koa?

### ISSUE THREAD

**Issue by tuananh** [RuntimeTools/appmetrics-zipkin#19]
Does it work with other web framework like koa?

**Comment by tobespc** [comment]
@tuananh Yes, it does work with koa.  I ran a simple test using this example

https://github.com/koajs/examples/blob/master/compose/app.js

and instrumented it with appmetrics-zipkin.  The traces did appear on the zipkin-ui

**Comment by tuananh** [comment]
i tested and it seems to work. however the duration is `NaN` sometimes.

**Comment by Eli-Goldberg** [comment]
It doesn't work with koa-bodyparser, which is kind of necessary for real-life apps.
Hoping to get it fixed / find another solution

**Comment by sjanuary** [comment]
@Eli-Goldberg what kind of error are you seeing, or is it just no data?
appmetrics-zipkin is open source, we're happy to accept pull requests if you would like to look into it. See https://github.com/RuntimeTools/appmetrics-zipkin/blob/master/CONTRIBUTING.md for more information.

**Comment by Eli-Goldberg** [comment]
@sjanuary 
sure :)
I've created a PR - https://github.com/RuntimeTools/appmetrics-zipkin/pull/32

**Comment by Eli-Goldberg** [comment]
Will work once #32 is approved.
This IMO this issue can be closed

**Comment by sjanuary** [comment]
#32 is merged so closing this issue
