### ISSUE TITLE
Receiving no spans following the readme

### ISSUE THREAD

**Issue by a-roberts** [RuntimeTools/appmetrics-zipkin#22]
Following the readme, getting no spans at all now.

```
var appzip = require('appmetrics-zipkin');
var express = require('express');
var app = express();

app.get('/api', (req, res) => res.send(new Date().toString()));
app.listen(9000, () => {
  console.log('Backend listening on port 9000!');
});
```

Start Zipkin, port 9411, change defaults so we can see **any** traces (start/end time adjustments, newest first, no limit).

Go to `localhost:9000/api`, see the server output OK.

No data.
![nodatazipkin](https://user-images.githubusercontent.com/12814972/33569696-6b685be6-d922-11e7-8f1a-2e7f11460ab7.png)

No data. Doesn't look to be trying to use Zipkin at all, even if I kill the Zipkin server I don't get any errors e.g. connection refused ones.

Tried appmetrics-zipkin 1.0.2 as well, node 6.12.0, node 6.10.3 (was on my path), node 8.9.0. Tried with

```
var appzip = require('appmetrics-zipkin')({
  host: 'localhost',
  port: 9411,
  serviceName:'frontend'
});
```

too.

package.json:

```
{
  "name": "easiest",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "dependencies": {
    "appmetrics-zipkin": "^1.0.3",
    "express": "^4.16.2"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC"
}
```

**Comment by sjanuary** [comment]
Some kind of API change between zipkin 0.10 and 0.11.  For now we've fixed the version we depend on to 0.10 since 0.x releases don't obey semver.
